name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  Windows:
    name: Windows
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        include:
          - os: windows-2019
            friendlyName: Windows
    timeout-minutes: 10
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0

      # This step can be removed as soon as official Windows arm64 builds are published:
      # https://github.com/nodejs/build/issues/2450#issuecomment-705853342
      - run: |
          $NodeVersion = (node --version) -replace '^.'
          $NodeFallbackVersion = "16.19.0"
          & .\script\download-node-lib-win-arm64.ps1 $NodeVersion $NodeFallbackVersion
        name: Install Windows arm64 node.lib

      - name: Install and build dependencies
        run: yarn

      - name: Prettify
        run: yarn prettify

      - name: Lint
        run: yarn check-prettier

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Prebuild x64
        run: yarn prebuild-napi-x64

      - name: Prebuild arm64
        run: yarn prebuild-napi-arm64

      - name: Prebuild x86
        run: yarn prebuild-napi-ia32

      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: yarn upload ${{ secrets.GITHUB_TOKEN }}

  Mac:
    name: Mac
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            friendlyName: Mac
    timeout-minutes: 10
    steps:
      - name: Check out git repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and build dependencies
        run: yarn

      - name: Prettify
        run: yarn prettify

      - name: Lint
        run: yarn check-prettier

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      - name: Prebuild x64
        run: yarn prebuild-napi-x64

      - name: Prebuild arm64
        run: yarn prebuild-napi-arm64

      - name: Publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: yarn upload ${{ secrets.GITHUB_TOKEN }}
